
version: '3.9'

services:
  superset:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: superset
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=nhanbui15122003@gmail.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'